<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Menu'); ?>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li><a href="/admin/module/stokes/add"><span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Add stoke'); ?></a></li>
         <li class="divider"></li>
         <li><a href="#" id="save-changes-btn"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Save changes'); ?></a></li>
         <li><a href="#" id="remove-selected-btn" data-button="remove-selected"><span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('Remove selected'); ?></a></li>
      </ul>
    </div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Pages')); ?>

<form>
    <table class="table table-hover table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th><input type="checkbox" /></th>
                <th><?php $this->show('#'); ?></th>
                <th><?php $this->show('Title'); ?></th>
                <th><?php $this->show('Default'); ?></th>
                <th><?php $this->show('SEO Enabled'); ?></th>
                <th><?php $this->show('Actions'); ?></th>
            </tr>
        </thead>
        
        <?php if (!empty($stokes)): ?>
        <tbody>
            <?php foreach ($stokes as $stoke): ?>
            <tr>
                <td><input type="checkbox" name="toDelete[<?php echo $stoke->id; ?>]" /></td>
                <td><?php echo $stoke->id; ?></td>
                <td><?php echo $stoke->title; ?></td>
                <td>
                    <?php echo Element::radio('default', $stoke->id, $stoke->default); ?>
                </td>
                <td>
                    <?php echo Element::checkbox(sprintf('seo[%s]', $stoke->id), $stoke->seoEnabled); ?>
                </td>
                <td>
                    <a data-button="view" href="<?php printf('/%s/', $stoke->slug); ?>"></a>
                    <a data-button="edit" href="<?php printf('/admin/module/pages/edit/%s', $stoke->id); ?>"></a>
                    <a data-button="delete" href="#" data-category="main" data-id="<?php echo $stoke->id; ?>"></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php endif; ?>
        
    </table>
</form>

<?php $this->loadBlock('paginator'); ?>

