<?php

use Krystal\Form\Element;

?>

<form data-group="stoke">
	<div class="well clearfix">
        <?php echo Element::hidden('stoke[id]', $stoke->getId()); ?>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('stoke[name]', $stoke->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Stoke name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('stoke[introduction]', $stoke->getIntroduction(), array('class' => 'form-control')); ?>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Full description'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::text('stoke[full]', $stoke->getIntroduction(), array('class' => 'form-control')); ?>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('stoke[keywords]', $stoke->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords for search engines'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Meta description'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('stoke[keywords]', $stoke->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
    </div>

    <?php if (!$stoke->getId()): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Stokes:Admin:Edit@indexAction', null); ?>" data-url="<?php echo $this->url('Stokes:Admin:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <?php else: ?>
    
    <button data-button="save" data-url="<?php echo $this->url('Stokes:Admin:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <?php endif; ?>
    
    <button data-button="cancel" data-url="<?php echo $this->url('Stokes:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
